"""add_ai_settings

Revision ID: 8bd24d9bf1df
Revises: 
Create Date: 2026-04-21 02:16:20.914370

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8bd24d9bf1df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AiSettings',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('RepoUrl', sa.String(length=500), nullable=False),
    sa.Column('GitToken', sa.String(length=500), nullable=True),
    sa.Column('WorkspacePath', sa.String(length=500), nullable=False),
    sa.Column('AnalysisMode', sa.String(length=20), nullable=False),
    sa.Column('AutoSync', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CreatedBy', sa.String(length=200), nullable=True),
    sa.Column('UpdatedBy', sa.String(length=200), nullable=True),
    sa.Column('IsDeleted', sa.Boolean(), nullable=False),
    sa.Column('DeletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('DeletedBy', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('__EFMigrationsHistory')
    op.alter_column('BranchTrackingRules', 'CreatedBy',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('BranchTrackingRules', 'UpdatedBy',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('BranchTrackingRules', 'DeletedBy',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index(op.f('IX_BranchTrackingRules_RepositoryId_Pattern'), table_name='BranchTrackingRules', postgresql_where='("DeletedAt" IS NULL)')
    op.create_index('ix_branchrules_repo_pattern', 'BranchTrackingRules', ['RepositoryId', 'Pattern'], unique=True)
    op.alter_column('Repositories', 'CloneUrl',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('Repositories', 'CreatedBy',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Repositories', 'UpdatedBy',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('Repositories', 'DeletedBy',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.create_foreign_key(None, 'Repositories', 'SourceProviders', ['ProviderId'], ['Id'])
    op.alter_column('RepositoryAuths', 'CreatedBy',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('RepositoryAuths', 'UpdatedBy',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('RepositoryAuths', 'DeletedBy',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index(op.f('IX_RepositoryAuths_RepositoryId'), table_name='RepositoryAuths')
    op.alter_column('SourceProviders', 'CreatedBy',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('SourceProviders', 'UpdatedBy',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('SourceProviders', 'DeletedBy',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index(op.f('IX_SourceProviders_Code'), table_name='SourceProviders')
    op.create_index('ix_sourceproviders_code', 'SourceProviders', ['Code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sourceproviders_code', table_name='SourceProviders')
    op.create_index(op.f('IX_SourceProviders_Code'), 'SourceProviders', ['Code'], unique=True)
    op.alter_column('SourceProviders', 'DeletedBy',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('SourceProviders', 'UpdatedBy',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('SourceProviders', 'CreatedBy',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('IX_RepositoryAuths_RepositoryId'), 'RepositoryAuths', ['RepositoryId'], unique=True)
    op.alter_column('RepositoryAuths', 'DeletedBy',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('RepositoryAuths', 'UpdatedBy',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('RepositoryAuths', 'CreatedBy',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'Repositories', type_='foreignkey')
    op.alter_column('Repositories', 'DeletedBy',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Repositories', 'UpdatedBy',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Repositories', 'CreatedBy',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Repositories', 'CloneUrl',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_index('ix_branchrules_repo_pattern', table_name='BranchTrackingRules')
    op.create_index(op.f('IX_BranchTrackingRules_RepositoryId_Pattern'), 'BranchTrackingRules', ['RepositoryId', 'Pattern'], unique=True, postgresql_where='("DeletedAt" IS NULL)')
    op.alter_column('BranchTrackingRules', 'DeletedBy',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('BranchTrackingRules', 'UpdatedBy',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('BranchTrackingRules', 'CreatedBy',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('__EFMigrationsHistory',
    sa.Column('MigrationId', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('ProductVersion', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('MigrationId', name=op.f('PK___EFMigrationsHistory'))
    )
    op.drop_table('AiSettings')
    # ### end Alembic commands ###
