"""drop_ai_settings

Revision ID: 8d6de8385f82
Revises: 94eb159a3a86
Create Date: 2026-04-21 03:09:54.818292

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8d6de8385f82'
down_revision: Union[str, None] = '94eb159a3a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AiSettings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AiSettings',
    sa.Column('Id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('WorkspacePath', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('AnalysisMode', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('AutoSync', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('CreatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('UpdatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('CreatedBy', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('UpdatedBy', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('IsDeleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('DeletedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('DeletedBy', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('RepositoryId', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['RepositoryId'], ['Repositories.Id'], name=op.f('AiSettings_RepositoryId_fkey')),
    sa.PrimaryKeyConstraint('Id', name=op.f('AiSettings_pkey'))
    )
    # ### end Alembic commands ###
