"""ai_settings_link_repository

Revision ID: 94eb159a3a86
Revises: 8bd24d9bf1df
Create Date: 2026-04-21 03:06:34.211003

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '94eb159a3a86'
down_revision: Union[str, None] = '8bd24d9bf1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AiSettings', sa.Column('RepositoryId', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'AiSettings', 'Repositories', ['RepositoryId'], ['Id'])
    op.drop_column('AiSettings', 'GitToken')
    op.drop_column('AiSettings', 'RepoUrl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AiSettings', sa.Column('RepoUrl', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('AiSettings', sa.Column('GitToken', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'AiSettings', type_='foreignkey')
    op.drop_column('AiSettings', 'RepositoryId')
    # ### end Alembic commands ###
