"""Add cloned_directory to Repository

Revision ID: baa460ab0f6f
Revises: 8d6de8385f82
Create Date: 2026-04-24 13:48:35.947356

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'baa460ab0f6f'
down_revision: Union[str, None] = '8d6de8385f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Repositories', sa.Column('ClonedDirectory', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Repositories', 'ClonedDirectory')
    # ### end Alembic commands ###
